apiVersion: apps/v1
kind: Deployment
metadata:
  name: iseya-task-management
  labels:
    app: iseya-task-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iseya-task-management
  template:
    metadata:
      labels:
        app: iseya-task-management
    spec:
      containers:
        - name: iseya-task-management
          image: gcr.io/balmy-elf-458808-p3/iseya-task-management:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: database-url
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: secret-key
            - name: ACCESS_TOKEN_EXPIRE_MINUTES
              value: "30"
            - name: JWT_ALGORITHM
              value: "HS256"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
