apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iseya-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - iseya.duckdns.org
      secretName: iseya-tls
  rules:
    - host: iseya.duckdns.org
      http:
        paths:
          - path: /?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: iseya-task-management
                port:
                  number: 80
